# Generated by Django 4.2.4 on 2023-09-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
