# Generated by Django 4.2.4 on 2023-09-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(unique=True, verbose_name='Номер версии'),
        ),
    ]
